services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      LANGLITE_DB_HOST: ${LANGLITE_DB_HOST}
      LANGLITE_DB_PORT: ${LANGLITE_DB_PORT}
      LANGLITE_DB_DATABASE: ${LANGLITE_DB_DATABASE}
      LANGLITE_DB_USERNAME: ${LANGLITE_DB_USERNAME}
      LANGLITE_DB_PASSWORD: ${LANGLITE_DB_PASSWORD}
      LANGLITE_DB_SCHEMA: ${LANGLITE_DB_SCHEMA}
      REDIS_ADDR: redis:6379
    volumes:
      - ./:/app
    depends_on:
      langlite_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - langlite
  langlite_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${LANGLITE_DB_DATABASE}
      POSTGRES_USER: ${LANGLITE_DB_USERNAME}
      POSTGRES_PASSWORD: ${LANGLITE_DB_PASSWORD}
    ports:
      - "${LANGLITE_DB_PORT}:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/setup_test_data.sql:/docker-entrypoint-initdb.d/02-test-data.sql
      - langlite_volume:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${LANGLITE_DB_USERNAME} -d ${LANGLITE_DB_DATABASE}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - langlite
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - langlite
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - langlite
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - langlite

volumes:
  langlite_volume:
  prometheus_data:
  grafana_data:
networks:
  langlite:
