services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      LANGLITE_DB_HOST: ${LANGLITE_DB_HOST}
      LANGLITE_DB_PORT: ${LANGLITE_DB_PORT}
      LANGLITE_DB_DATABASE: ${LANGLITE_DB_DATABASE}
      LANGLITE_DB_USERNAME: ${LANGLITE_DB_USERNAME}
      LANGLITE_DB_PASSWORD: ${LANGLITE_DB_PASSWORD}
      LANGLITE_DB_SCHEMA: ${LANGLITE_DB_SCHEMA}
      REDIS_ADDR: redis:6379
    volumes:
      - ./:/app
    depends_on:
      langlite_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - langlite
  langlite_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${LANGLITE_DB_DATABASE}
      POSTGRES_USER: ${LANGLITE_DB_USERNAME}
      POSTGRES_PASSWORD: ${LANGLITE_DB_PASSWORD}
    ports:
      - "${LANGLITE_DB_PORT}:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./setup_test_data.sql:/docker-entrypoint-initdb.d/02-test-data.sql
      - langlite_volume:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${LANGLITE_DB_USERNAME} -d ${LANGLITE_DB_DATABASE}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - langlite
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - langlite

volumes:
  langlite_volume:
networks:
  langlite:
