global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "sample.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "langlite-api"
    static_configs:
      - targets: ["app:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s
# Future: Remote write configuration for migration to managed Prometheus
# remote_write:
#   - url: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
#     basic_auth:
#       username: "your-username"
#       password: "your-api-key"

